apiVersion: v1
kind: Service
metadata:
  name: metrcis-postgres-service
  namespace: metrics-demo
spec:
  selector:
    app: metrics-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP